### ISSUE TITLE
`data/areas-of-interest`: locate spatial data, download into Gdrive, and organize for reading in R

### ISSUE THREAD

**Issue by bbest** [CalCOFI/scripts#5]
Locate spatial data from [Erin's list](https://github.com/CalCOFI/scripts/issues/3#issuecomment-1021582212), download into Google Drive into `areas-of-interest` folder under [data/](https://drive.google.com/drive/folders/1xxdWa4mWkmfkJUQsHxERTp9eBBXBMbV7), and read into R (e.g. with `sf::read_sf()`
- add subfolders per AOI
- add `README.md` with:
  - URL:
  - Date accessed:
  - Citation(s):
  - Notes:

I think these are the main ones -- added some specificity below:

## CalCOFI
- [x] CalCOFI study area
 >>CalCOFI Regions-- Station # > 60 = oceanic/offshore; <60 = neritic/nearshore/continental shelf (other regions include those from [Venrick et al. 2012]( http://calcofi.org/publications/calcofireports/v56/Vol56-Venrick.web.168-184.pdf) or [Stephens et al. 2018](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2018GB005930)
  [data/calcofi_oceano-bottle-stations_convex-hull.geojson](https://github.com/CalCOFI/scripts/blob/dc2e72c7b159ab65a639a6b3f50b847f358e617b/data/calcofi_oceano-bottle-stations_convex-hull.geojson) made with [oceano-bottle.Rmd](https://github.com/CalCOFI/scripts/blob/dc2e72c7b159ab65a639a6b3f50b847f358e617b/oceano-bottle.Rmd#L108):
  ![image](https://user-images.githubusercontent.com/2837257/154581062-70d54e5c-7856-4256-8935-231f1e2eb2ef.png)
  also [nearshore](https://github.com/CalCOFI/scripts/blob/da5cee7ce42191fe4d1d7403528dd751e10ae83e/data/calcofi_oceano-bottle-stations_convex-hull_nearshore.geojson)/[offshore variants](https://github.com/CalCOFI/scripts/blob/da5cee7ce42191fe4d1d7403528dd751e10ae83e/data/calcofi_oceano-bottle-stations_convex-hull_offshore.geojson) made with [oceano-bottle.Rmd](https://github.com/CalCOFI/scripts/blob/da5cee7ce42191fe4d1d7403528dd751e10ae83e/oceano-bottle.Rmd#L125-L131)

## International

- [x] Territorial <12nm
- [x] High Seas >12nm

## Federal

- [x] Sanctuaries: [sanctuaries.geojson](https://github.com/noaa-onms/onmsR/blob/master/data-raw/sanctuaries.geojson)
  -  Channel Islands NMS
  -  Monterey Bay NMS
  -  Chumash Heritage NMS (proposed)

- [x] IEA California Current
- [x] Freshwater ecoregion - SoCal Bight
- [ ] CCE biological sampling areas (Central CCE, Southern CCE)- https://www.pcouncil.org/documents/2020/02/g-1-a-iea-team-report-1.pdf/
- [x] Federal waters: 3-12nm  (see image on page 16 http://www.opc.ca.gov/webmaster/ftp/pdf/docs/Documents_Page/Noteworthy/Overview_Ocean_Coastal_Laws.pdf)
- [x] EEZ federal: 3 (12?) to 200 nm (see MarineCadastre.org) OR (see image on page 16 http://www.opc.ca.gov/webmaster/ftp/pdf/docs/Documents_Page/Noteworthy/Overview_Ocean_Coastal_Laws.pdf)

### BOEM
- [x] Wind Energy Areas
- [x] OCS- Central/Southern (https://www.boem.gov/sites/default/files/documents/about-boem/POCS%20Environmental%20Setting%20Report%20FINAL%202020-02-18.pdf)
- [x] aliquots, etc

## State
- [x] CDFW Districts (https://wildlife.ca.gov/Fishing/Commercial/Regulations/Districts)
- [x] CCAs (https://nrm.dfg.ca.gov/FileHandler.ashx?DocumentID=36132&inline)
- [x] MPAs (only ones that have CalCOFI stations in them?) 
- [x] State Assembly Districts?- http://www.legislature.ca.gov/assemblydistricts.html
- [x] Senate Districts?- http://www.legislature.ca.gov/Final_2013_2014_Senate_Map_v2.pdf
- [x] State waters: 0-3nm (see image on page 16 http://www.opc.ca.gov/webmaster/ftp/pdf/docs/Documents_Page/Noteworthy/Overview_Ocean_Coastal_Laws.pdf)

## County/local
- [x] Counties (https://www.counties.org/sites/main/files/file-attachments/california_county_map_0.pdf)
- [x] Sanitation districts (not sure how defined -- https://en.wikipedia.org/wiki/Metropolitan_Water_District_of_Southern_California#/media/File:Metropolitan_Water_Districts_Member_Agencies_Map.jpg)
- [x] Ports (not exactly sure how to designate -- maybe based on city bounds?)
- [x] Watershed HUCs (pollutant modeling) (https://databasin.org/maps/8de1d4f19adf4fb7a10df7877bce8101/active/)
- [x] Areas of Special Biological Significance - "34 ocean areas monitored and maintained for water quality by the State Water Resources Control Board"- (https://www.waterboards.ca.gov/water_issues/programs/ocean/asbs_map.shtml)

## Overlap strategy

We don't need to keep features that do not intersect CalCOFI study area, eg Sanctuaries on the East Coast, but we don't want to clip intersecting features to the study area, ie keep the original polygon shape. So technically, that means keep all `sf::st_intersects()` (not `sf::st_intersection()`).

## Motivation

Goal: Get AOIs that intersect CalCOFI study area for extraction of key variables over time, a la ...

https://shiny.ecoquants.com/calcofi/

![image](https://user-images.githubusercontent.com/2837257/154577180-6a6068b3-18a5-49fe-854a-230fb4ae89e2.png)

**Comment by superjai** [comment]
Hey @bbest. Question on what to do for polygons that extend far beyond the calcofi study area. The biggest example here is with territorial and non-territorial waters. I have found these polygons no problem (available [here](https://nauticalcharts.noaa.gov/data/us-maritime-limits-and-boundaries.html) and [here](https://www.marineregions.org/downloads.php)), but these polygons extend way beyond the california zone., which is obviously too much. Should I clip the waters polygons to the boundary of the calcofi study area that you already found?

**Comment by bbest** [comment]
Hi @superjai, please read the Overlap Strategy heading above in this issue. We don’t want to clip, just retain any features that intersect. I’d start by downloading any relevant ones into Google Drive. Then run through intersecting, ideally with an R script or similar.

**Comment by bbest** [comment]
Please be sure to include a README with source URL in the Gdrive folders and check Task boxes as you go. Thanks!

**Comment by superjai** [comment]
Hey @bbest - I have gotten as far as I can with this one and I have sent emails out where I have had issues. All of the requested datasets have been saved to the google drive, with the following exceptions:

- IEA California Current (I can't find it online. Sent email to Chris Harvey requesting access)
 - CCE biological sampling areas (I can't find it online. Sent email to Chris Harvey requesting access)
 - BOEM Outer Continental Shelf - "Central/Southern" (This area is actually never actually defined in the report that Erin listed as a resource. I had some suggestions how to proceed and I emailed Erin asking how she wanted to go).
 -  BOEM "aliquots, etc" (Two issues here. First it seems like Erin wanted something beyond just aliquot data and I emailed her what additionally she was looking for. Second, the BOEM aliquot data is not available due to a 404 error at the associated data portal. I emailed BOEM to inquire where the data might be).
 - "Ports (not exactly sure how to designate -- maybe based on city bounds?)" - there are two kinds of port data available for california, fishing ports and shipping ports. I emailed Erin to clarify which she was looking for.

**Comment by superjai** [comment]
Response from Erin:
I was looking at this data (https://www.boem.gov/oil-gas-energy/mapping-and-data/pacific-cadastral-data) and was thinking of: 
1. Pacific Planning Area Outlines (I can't tell if these are the same as the OCS boundaries...)
2. Standard OCS Blocks clipped to the Submerged Lands Act (SLA) boundary on the shoreward side (2304 hectares per standard block).
3. Active Leases

**Comment by bbest** [comment]
Q: What about the terrestrial layers, like Counties and Ports?

## Create non-overlapping buffers for terrestrial layers

See https://ohi-science.org/pages/create_regions.html for ArcGIS Python script to handle this.
![](https://ohi-science.org/figs/create_regions/buffers.png)

* Maybe R solution here: [Couple of questions about buffers and MPAs in LSP · Issue #17 · OHI-Science/ohi-science.github.io](https://github.com/OHI-Science/ohi-science.github.io/issues/17#issuecomment-253856068)

**Comment by superjai** [comment]
Note! I couldn’t actually check to see if the "IEA regions" shapefile contains the desired IEA regions. Attempting to open this shapefile in RStudio caused an immediate crash of RStudio. I nonetheless saved the shapefile to the google drive.

**Comment by superjai** [comment]
All the data layers have now been grabbed with the exception of "CCE biological sampling areas", which is unavailable. Here's the note from Chris Harvey, NOAA scientist, who generated that sampling area map:

JAI: In the following report for which you were the lead, I was hoping to get the shapefiles you used to generate two of your figures: https://www.pcouncil.org/documents/2020/02/g-1-a-iea-team-report-1.pdf/
A. I was hoping you could direct me to the shapefiles used in Figure 2.1.a. for "oceanographic sampling locations".
B. Additionally, I was looking for the shapefiles used in Figure 2.1.c for "biological sampling areas".

CHRIS: That Figure 2 is the worst...I basically made those panels myself in Powerpoint with some screen captures and crude artwork, and frankly my computer skills are pretty limited, so there aren't any shape files per se. I'm happy to share those images with you but they're terrible and a bit out-of-date, and they've been on my list of things to improve for several years.

**Comment by bbest** [comment]
Ok, this is great Jai! Thanks for gathering all the data. We'll leave out the CCE biological sampling areas per Chris' comment.
